name: CI

on: [push]

jobs:
  sync:
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.AUTH_TOKEN }}'
          project-id: '${{ secrets.PROJECT_ID }}'
